apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: prod
  labels:
    app: discovery-service
spec:
  selector:
    matchLabels:
      app: discovery-service
  # 앱이 Ready 상태가 될 때까지 기다리는 시간
  minReadySeconds: 10
  # 롤링 업데이트:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 롤링 업데이트시 스케일아웃할 최대 pod 수
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: discovery-pod
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: ${ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${IMAGE_TAG}
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8761
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      affinity:
        nodeAffinity:
          # Pod이 존재하지 않다가 처음으로 만들어지는 상태, 이미 실행중인데 nodeSelector가 node에서 제거된다면 계속 실행
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - App
                  - key: size
                    operator: In
                    values:
                      - Large
                      - Medium
