FROM amazoncorretto:11-alpine

WORKDIR /app

ENV PROFILES=prod

ARG ORIGINAL_JAR_FILE=./build/libs/discovery-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} discovery-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/discovery-service.jar"]
